production:
  default: &default
  adapter: postgresql
  encoding: unicode
  database: dcmonitors
  host: localhost
  pool: 5
  username: dcmonitor
  password: dcmonitor
  
test:
  default: &default
  adapter: sqlite3
  encoding: unicode
  database: db_dev_db.sqlite3
  host: localhost
  pool: 5
  
development:
  default: &default
  adapter: sqlite3
  encoding: unicode
  database: db_dev_db.sqlite3
  host: localhost
  pool: 5

